# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeed',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
